projects:
  app:
    schemaPath: src/schema/main.graphql
    extensions:
      endpoints:
        default: http://localhost:4000
  database:
    schemaPath: src/schema/generated/database.graphql
    extensions:
      prisma: database/prisma.yml
